services:
  # The FastAPI backend service
  optik_backend:
    build: .
    container_name: optik_fastapi_backend
    command: uvicorn main:app --host 0.0.0.0 --port 8002 --reload
    volumes:
      - .:/app
    ports:
      - "8002:8002"
    # Load environment variables from a .env file
    env_file:
      - ./.env
    # Environment variables needed by the FastAPI application
    # These are now dynamically set from the .env file
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@optik_db:${POSTGRES_PORT}/${POSTGRES_DB}
    depends_on:
      optik_db:
        condition: service_healthy
      optik_alembic:
        condition: service_completed_successfully

  # The PostgreSQL database service
  optik_db:
    image: postgres:15-alpine
    container_name: optik_postgres_db
    volumes:
      - optik_postgres_data:/var/lib/postgresql/data/
    # Load environment variables from a .env file
    env_file:
      - ./.env
    # Environment variables to configure the PostgreSQL instance
    # These are now dynamically set from the .env file
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  optik_alembic:
    build: .
    container_name: optik_alembic_migration
    env_file:
      - ./.env
    depends_on:
      optik_db:
        condition: service_healthy
    command: ['alembic', 'upgrade', 'head']
    profiles:
      - migration

# Define the named volume for data persistence
volumes:
  optik_postgres_data:
