services:
  # The FastAPI backend service
  backend:
    build: .
    container_name: fastapi_backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    # Load environment variables from a .env file
    env_file:
      - ./.env
    # Environment variables needed by the FastAPI application
    # These are now dynamically set from the .env file
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}
    depends_on:
      db:
        condition: service_healthy

  # The PostgreSQL database service
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    # Load environment variables from a .env file
    env_file:
      - ./.env
    # Environment variables to configure the PostgreSQL instance
    # These are now dynamically set from the .env file
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  alembic:
    build: .
    container_name: alembic-migration
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
    command: ['alembic', 'upgrade', 'head']
    profiles:
      - migration

# Define the named volume for data persistence
volumes:
  postgres_data:
