"""Add item code and name snapshots to transaction items

Revision ID: 3cea117fad61
Revises: c9f1a2b3d4e5
Create Date: 2026-03-08 21:45:28.203225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3cea117fad61'
down_revision: Union[str, Sequence[str], None] = 'c9f1a2b3d4e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inventory', 'additional_note',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('purchase_transaction', 'notes',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.add_column('purchase_transaction_item', sa.Column('item_code_snapshot', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('purchase_transaction_item', sa.Column('item_name_snapshot', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_constraint('purchase_transaction_item_inventory_id_fkey', 'purchase_transaction_item', type_='foreignkey')
    op.drop_constraint('purchase_transaction_item_purchase_transaction_id_fkey', 'purchase_transaction_item', type_='foreignkey')
    op.create_foreign_key(None, 'purchase_transaction_item', 'purchase_transaction', ['purchase_transaction_id'], ['id'])
    op.create_foreign_key(None, 'purchase_transaction_item', 'inventory', ['inventory_id'], ['kode_barang'], ondelete='SET NULL')
    op.alter_column('sales_transaction', 'notes',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.add_column('sales_transaction_item', sa.Column('item_code_snapshot', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('sales_transaction_item', sa.Column('item_name_snapshot', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_constraint('sales_transaction_item_inventory_id_fkey', 'sales_transaction_item', type_='foreignkey')
    op.drop_constraint('sales_transaction_item_sales_transaction_id_fkey', 'sales_transaction_item', type_='foreignkey')
    op.create_foreign_key(None, 'sales_transaction_item', 'sales_transaction', ['sales_transaction_id'], ['id'])
    op.create_foreign_key(None, 'sales_transaction_item', 'inventory', ['inventory_id'], ['kode_barang'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales_transaction_item', type_='foreignkey')
    op.drop_constraint(None, 'sales_transaction_item', type_='foreignkey')
    op.create_foreign_key('sales_transaction_item_sales_transaction_id_fkey', 'sales_transaction_item', 'sales_transaction', ['sales_transaction_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('sales_transaction_item_inventory_id_fkey', 'sales_transaction_item', 'inventory', ['inventory_id'], ['kode_barang'])
    op.drop_column('sales_transaction_item', 'item_name_snapshot')
    op.drop_column('sales_transaction_item', 'item_code_snapshot')
    op.alter_column('sales_transaction', 'notes',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'purchase_transaction_item', type_='foreignkey')
    op.drop_constraint(None, 'purchase_transaction_item', type_='foreignkey')
    op.create_foreign_key('purchase_transaction_item_purchase_transaction_id_fkey', 'purchase_transaction_item', 'purchase_transaction', ['purchase_transaction_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('purchase_transaction_item_inventory_id_fkey', 'purchase_transaction_item', 'inventory', ['inventory_id'], ['kode_barang'])
    op.drop_column('purchase_transaction_item', 'item_name_snapshot')
    op.drop_column('purchase_transaction_item', 'item_code_snapshot')
    op.alter_column('purchase_transaction', 'notes',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('inventory', 'additional_note',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    # ### end Alembic commands ###
