"""Add cascade delete to sales transaction relationships

Revision ID: 40de804c9725
Revises: a529a36c1c67
Create Date: 2025-08-24 09:48:29.119104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40de804c9725'
down_revision: Union[str, Sequence[str], None] = 'a529a36c1c67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('account_receivable', 'buyer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('fk_account_receivable_buyer_id'), 'account_receivable', type_='foreignkey')
    op.create_foreign_key(None, 'account_receivable', 'buyer', ['buyer_id'], ['id'])
    op.alter_column('sales_transaction', 'buyer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sales_transaction', 'inventory_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_constraint(op.f('fk_sales_transaction_inventory_id'), 'sales_transaction', type_='foreignkey')
    op.drop_constraint(op.f('fk_sales_transaction_buyer_id'), 'sales_transaction', type_='foreignkey')
    op.create_foreign_key(None, 'sales_transaction', 'inventory', ['inventory_id'], ['id'])
    op.create_foreign_key(None, 'sales_transaction', 'buyer', ['buyer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales_transaction', type_='foreignkey')
    op.drop_constraint(None, 'sales_transaction', type_='foreignkey')
    op.create_foreign_key(op.f('fk_sales_transaction_buyer_id'), 'sales_transaction', 'buyer', ['buyer_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_sales_transaction_inventory_id'), 'sales_transaction', 'inventory', ['inventory_id'], ['id'], ondelete='CASCADE')
    op.alter_column('sales_transaction', 'inventory_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('sales_transaction', 'buyer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'account_receivable', type_='foreignkey')
    op.create_foreign_key(op.f('fk_account_receivable_buyer_id'), 'account_receivable', 'buyer', ['buyer_id'], ['id'], ondelete='CASCADE')
    op.alter_column('account_receivable', 'buyer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
