"""Create initial tables

Revision ID: a6343b73b898
Revises: 
Create Date: 2025-08-23 23:35:40.290388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# SQLModel is not needed here, but importing sa is standard
# import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a6343b73b898'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buyer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone_num', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buyer_name'), 'buyer', ['name'], unique=False)
    op.create_table('inventory',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('roll_count', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('bale_count', sa.Integer(), nullable=True),
    sa.Column('price_per_kg', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_name'), 'inventory', ['name'], unique=False)
    op.create_table('account_receivable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('age_0_30_days', sa.Integer(), nullable=True),
    sa.Column('age_31_60_days', sa.Integer(), nullable=True),
    sa.Column('age_61_90_days', sa.Integer(), nullable=True),
    sa.Column('age_over_90_days', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_receivable_buyer_id'), 'account_receivable', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_account_receivable_period'), 'account_receivable', ['period'], unique=False)
    op.create_table('sales_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('inventory_id', sa.String(length=50), nullable=False),
    sa.Column('roll_count', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('price_per_kg', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyer.id'], ),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_transaction_buyer_id'), 'sales_transaction', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_sales_transaction_inventory_id'), 'sales_transaction', ['inventory_id'], unique=False)
    op.create_index(op.f('ix_sales_transaction_transaction_date'), 'sales_transaction', ['transaction_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_transaction_transaction_date'), table_name='sales_transaction')
    op.drop_index(op.f('ix_sales_transaction_inventory_id'), table_name='sales_transaction')
    op.drop_index(op.f('ix_sales_transaction_buyer_id'), table_name='sales_transaction')
    op.drop_table('sales_transaction')
    op.drop_index(op.f('ix_account_receivable_period'), table_name='account_receivable')
    op.drop_index(op.f('ix_account_receivable_buyer_id'), table_name='account_receivable')
    op.drop_table('account_receivable')
    op.drop_index(op.f('ix_inventory_name'), table_name='inventory')
    op.drop_table('inventory')
    op.drop_index(op.f('ix_buyer_name'), table_name='buyer')
    op.drop_table('buyer')
    # ### end Alembic commands ###