"""init table

Revision ID: e13b653d5b2b
Revises: 
Create Date: 2025-10-08 22:33:16.581748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e13b653d5b2b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create ENUM type for InventoryType
    inventory_type_enum = sa.Enum('FABRIC', 'THREAD', name='inventorytype')
    inventory_type_enum.create(op.get_bind(), checkfirst=True)
    
    # --- Create Tables with No Foreign Key Dependencies on other new tables ---
    op.create_table('buyer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone_num', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buyer_name'), 'buyer', ['name'], unique=False)
    
    op.create_table('inventory',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', inventory_type_enum, nullable=False),
    sa.Column('bale_ratio', sa.Float(), nullable=True),
    sa.Column('roll_count', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('bale_count', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_name'), 'inventory', ['name'], unique=False)
    op.create_index(op.f('ix_inventory_type'), 'inventory', ['type'], unique=False)
    
    op.create_table('machine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_machine_name'), 'machine', ['name'], unique=True)
    
    op.create_table('operator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone_num', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operator_name'), 'operator', ['name'], unique=False)
    
    op.create_table('supplier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone_num', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_name'), 'supplier', ['name'], unique=False)
    
    # --- Create Tables with Foreign Key Dependencies ---
    op.create_table('account_receivable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=True),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('age_0_30_days', sa.Float(), nullable=True),
    sa.Column('age_31_60_days', sa.Float(), nullable=True),
    sa.Column('age_61_90_days', sa.Float(), nullable=True),
    sa.Column('age_over_90_days', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_receivable_buyer_id'), 'account_receivable', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_account_receivable_period'), 'account_receivable', ['period'], unique=False)
    
    op.create_table('dyeing_process',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('dyeing_weight', sa.Float(), nullable=False),
    sa.Column('dyeing_final_weight', sa.Float(), nullable=True),
    sa.Column('dyeing_roll_count', sa.Float(), nullable=True),
    sa.Column('dyeing_overhead_cost', sa.Float(), nullable=True),
    sa.Column('dyeing_status', sa.Boolean(), nullable=False),
    sa.Column('dyeing_note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['inventory.id'], ),
    sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_dyeing_process_dyeing_status'), 'dyeing_process', ['dyeing_status'], unique=False)
    op.create_index(op.f('ix_dyeing_process_end_date'), 'dyeing_process', ['end_date'], unique=False)
    op.create_index(op.f('ix_dyeing_process_start_date'), 'dyeing_process', ['start_date'], unique=False)
    
    op.create_table('knit_formula',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('formula', sa.JSON(), nullable=False),
    sa.Column('production_weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['inventory.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_index(op.f('ix_knit_formula_product_id'), 'knit_formula', ['product_id'], unique=True)
    
    op.create_table('purchase_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('inventory_id', sa.String(), nullable=True),
    sa.Column('bale_count', sa.Float(), nullable=True),
    sa.Column('roll_count', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('price_per_kg', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_transaction_inventory_id'), 'purchase_transaction', ['inventory_id'], unique=False)
    op.create_index(op.f('ix_purchase_transaction_supplier_id'), 'purchase_transaction', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_purchase_transaction_transaction_date'), 'purchase_transaction', ['transaction_date'], unique=False)
    
    op.create_table('sales_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=True),
    sa.Column('inventory_id', sa.String(), nullable=True),
    sa.Column('roll_count', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('price_per_kg', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyer.id'], ),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_transaction_buyer_id'), 'sales_transaction', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_sales_transaction_inventory_id'), 'sales_transaction', ['inventory_id'], unique=False)
    op.create_index(op.f('ix_sales_transaction_transaction_date'), 'sales_transaction', ['transaction_date'], unique=False)
    
    op.create_table('knitting_process',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('knit_formula_id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('knit_status', sa.Boolean(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('roll_count', sa.Float(), nullable=True),
    sa.Column('materials', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['knit_formula_id'], ['knit_formula.id'], ),
    sa.ForeignKeyConstraint(['machine_id'], ['machine.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['operator.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knitting_process_end_date'), 'knitting_process', ['end_date'], unique=False)
    op.create_index(op.f('ix_knitting_process_knit_formula_id'), 'knitting_process', ['knit_formula_id'], unique=False)
    op.create_index(op.f('ix_knitting_process_knit_status'), 'knitting_process', ['knit_status'], unique=False)
    op.create_index(op.f('ix_knitting_process_machine_id'), 'knitting_process', ['machine_id'], unique=False)
    op.create_index(op.f('ix_knitting_process_operator_id'), 'knitting_process', ['operator_id'], unique=False)
    op.create_index(op.f('ix_knitting_process_start_date'), 'knitting_process', ['start_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop tables in reverse order of creation to satisfy FK constraints
    op.drop_index(op.f('ix_knitting_process_start_date'), table_name='knitting_process')
    op.drop_index(op.f('ix_knitting_process_operator_id'), table_name='knitting_process')
    op.drop_index(op.f('ix_knitting_process_machine_id'), table_name='knitting_process')
    op.drop_index(op.f('ix_knitting_process_knit_status'), table_name='knitting_process')
    op.drop_index(op.f('ix_knitting_process_knit_formula_id'), table_name='knitting_process')
    op.drop_index(op.f('ix_knitting_process_end_date'), table_name='knitting_process')
    op.drop_table('knitting_process')
    
    op.drop_index(op.f('ix_sales_transaction_transaction_date'), table_name='sales_transaction')
    op.drop_index(op.f('ix_sales_transaction_inventory_id'), table_name='sales_transaction')
    op.drop_index(op.f('ix_sales_transaction_buyer_id'), table_name='sales_transaction')
    op.drop_table('sales_transaction')
    
    op.drop_index(op.f('ix_purchase_transaction_transaction_date'), table_name='purchase_transaction')
    op.drop_index(op.f('ix_purchase_transaction_supplier_id'), table_name='purchase_transaction')
    op.drop_index(op.f('ix_purchase_transaction_inventory_id'), table_name='purchase_transaction')
    op.drop_table('purchase_transaction')
    
    op.drop_index(op.f('ix_knit_formula_product_id'), table_name='knit_formula')
    op.drop_table('knit_formula')
    
    op.drop_index(op.f('ix_dyeing_process_start_date'), table_name='dyeing_process')
    op.drop_index(op.f('ix_dyeing_process_product_id'), table_name='dyeing_process')
    op.drop_index(op.f('ix_dyeing_process_end_date'), table_name='dyeing_process')
    op.drop_index(op.f('ix_dyeing_process_dyeing_status'), table_name='dyeing_process')
    op.drop_table('dyeing_process')
    
    op.drop_index(op.f('ix_account_receivable_period'), table_name='account_receivable')
    op.drop_index(op.f('ix_account_receivable_buyer_id'), table_name='account_receivable')
    op.drop_table('account_receivable')
    
    op.drop_index(op.f('ix_supplier_name'), table_name='supplier')
    op.drop_table('supplier')
    
    op.drop_index(op.f('ix_operator_name'), table_name='operator')
    op.drop_table('operator')
    
    op.drop_index(op.f('ix_machine_name'), table_name='machine')
    op.drop_table('machine')
    
    op.drop_index(op.f('ix_inventory_type'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_name'), table_name='inventory')
    op.drop_table('inventory')
    
    op.drop_index(op.f('ix_buyer_name'), table_name='buyer')
    op.drop_table('buyer')

    # Drop the ENUM type
    inventory_type_enum = sa.Enum('FABRIC', 'THREAD', name='inventorytype')
    inventory_type_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###